# Generated by Django 4.2 on 2025-03-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=50, verbose_name='Resolución')),
                ('cod', models.CharField(max_length=50, verbose_name='Código')),
                ('expte', models.CharField(max_length=100, verbose_name='Expediente')),
                ('tema', models.TextField(verbose_name='Tema')),
                ('pdf', models.URLField(verbose_name='Enlace PDF')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
            ],
        ),
    ]
